#importação da biblioteca dentro do kv é obrigatoria
#:import Factory kivy.factory.Factory
<MenuPrinc@BoxLayout>:
    BoxLayout:
        size_hint:1,None
        height:dp(66)
        Button:
            text:"Click para Popup"
            size_hint:1, None
            height:dp(66)
            on_press:
                Factory.Pop().open()


<Pop@Popup>:
    auto_dismiss: False
    Button:
        text: 'Close me!'
        on_release: root.dismiss()

MenuPrinc: